version: '3'
services:
  signal-appconfig:
    image: 923839683/aws-appconfig-emulator:1.0.0
    container_name: signal-appconfig
    restart: always
    platform: linux/amd64
    volumes:
      - ./appconfig/config.yml:/go/release/config.yml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9007" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.0.2

  signal-dynamodb:
    image: amazon/dynamodb-local:1.18.0
    container_name: signal-dynamodb
    restart: always
    volumes:
      - ./dynamodb/data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.0.3

  signal-redis-cluster1:
    image: redis:7.0.4-bullseye
    container_name: signal-redis-cluster1
    restart: always
    volumes:
      - ./cache/docker/signal-redis-cluster1:/data
      - ./redis/cluster/redis.conf:/etc/redis/redis.conf
    command: 'sh -c "redis-server /etc/redis/redis.conf"'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.1.1
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=172.23.1.1
  signal-redis-cluster2:
    image: redis:7.0.4-bullseye
    container_name: signal-redis-cluster2
    restart: always
    volumes:
      - ./cache/docker/signal-redis-cluster2:/data
      - ./redis/cluster/redis.conf:/etc/redis/redis.conf
    command: 'sh -c "redis-server /etc/redis/redis.conf"'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.1.2
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=172.23.1.2
  signal-redis-cluster3:
    image: redis:7.0.4-bullseye
    container_name: signal-redis-cluster3
    restart: always
    volumes:
      - ./cache/docker/signal-redis-cluster3:/data
      - ./redis/cluster/redis.conf:/etc/redis/redis.conf
    command: 'sh -c "redis-server /etc/redis/redis.conf"'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.1.3
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=172.23.1.3
  signal-redis-cluster4:
    image: redis:7.0.4-bullseye
    container_name: signal-redis-cluster4
    restart: always
    volumes:
      - ./cache/docker/signal-redis-cluster4:/data
      - ./redis/cluster/redis.conf:/etc/redis/redis.conf
    command: 'sh -c "redis-server /etc/redis/redis.conf"'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.1.4
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=172.23.1.4
  signal-redis-cluster5:
    image: redis:7.0.4-bullseye
    container_name: signal-redis-cluster5
    restart: always
    volumes:
      - ./cache/docker/signal-redis-cluster5:/data
      - ./redis/cluster/redis.conf:/etc/redis/redis.conf
    command: 'sh -c "redis-server /etc/redis/redis.conf"'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.1.5
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=172.23.1.5
  signal-redis-cluster6:
    image: redis:7.0.4-bullseye
    container_name: signal-redis-cluster6
    restart: always
    volumes:
      - ./cache/docker/signal-redis-cluster6:/data
      - ./redis/cluster/redis.conf:/etc/redis/redis.conf
    command: 'sh -c "redis-server /etc/redis/redis.conf"'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      signal_network:
        ipv4_address: 172.23.1.6
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=172.23.1.6
  signal-redis-cluster-starter:
    image: redis:7.0.4-bullseye
    container_name: signal-redis-cluster-starter
    restart: 'no'
    command: 'sh /myapp/start.sh'
    volumes:
      - ./redis/cluster/start.sh:/myapp/start.sh
    healthcheck:
      test: [ "CMD", "cat", "/tmp/finish" ]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      - signal-redis-cluster1
      - signal-redis-cluster2
      - signal-redis-cluster3
      - signal-redis-cluster4
      - signal-redis-cluster5
      - signal-redis-cluster6
    networks:
      signal_network:
        ipv4_address: 172.23.1.100

  signal-server:
    image: maven:3.8.6-openjdk-18
    container_name: signal-server
    restart: "no"
    volumes:
      - ./cache/docker/maven_3.8.6-openjdk-18:/root/.m2
      - ./signal-server/app/:/myapp
      - ./signal-server/src/:/git/src
    command: "bash /myapp/start.sh"
    networks:
      signal_network:
        ipv4_address: 172.23.200.1
    depends_on:
      - signal-appconfig
      - signal-redis-cluster-starter

networks:
  signal_network:
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1